version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    shm_size: 128mb
     

    environment:
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
