services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
